### 404 route Not Found
GET http://localhost:4000/abc_xyz

###Get a list of all people
GET http://localhost:3000/people

### Create a people
POST http://localhost:3000/people
Content-Type: application/json

{
  "first_name": "Juan",
  "last_name": "Manual",
  "gender":"Male",
  "class":6
}

### GET a people by id
GET http://localhost:3000/people/638e8f0f07c6035050de7417

### Update a people by id
PATCH  http://localhost:3000/people/638e8f0f07c6035050de7417
Content-Type: application/json

{
  "class":10
}

### Delete a people by id
DELETE  http://localhost:3000/people/638e8f0f07c6035050de7417




































#hrXWgw4Q127uqZJ3